FROM php:5.5-fpm-alpine

#RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
#RUN apt-get update && apt-get upgrade -y

FROM mysql:latest
ENV MYSQLROOT=spass
#            MYSQL_USER: MYSQL_USER
#            MYSQL_PASSWORD: MYSQL_PASSWORD