apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    label-key1: labelala
  annotations:
    annotation-key1: annotlala
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: podnginxRC
      labels:
        app : nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
