apiVersion: v1
kind: Pod
metadata:
  name: podnginx
  labels:
    label-key1: podnginxprobe
  annotations:
    annotation-key1: annotation-value
    annotation-key2: pode ini menggunakan images nginx label anotation dan key
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
